app:
    resource: "@AppBundle/Controller/"
    type:     annotation

_home:
    path: /
    defaults: { _controller: AppBundle:Default:index }

_dewerf:
    path: /dewerf
    defaults: { _controller: AppBundle:Default:dewerf }

_berging:
    path: /winterberging
    defaults: { _controller: AppBundle:Default:berging }

_tarieven:
    path: /tarieven
    defaults: { _controller: AppBundle:Default:tarieven }

_verkoop:
    path: /verkoop
    defaults: { _controller: AppBundle:Default:verkoop }

_contact:
    path: /contact
    defaults: { _controller: AppBundle:Default:contact }
